# Generated by Django 5.0.6 on 2024-06-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='banner',
            field=models.ImageField(blank=True, default='banners/default.jpg', upload_to='banners/'),
        ),
    ]
